[workspace]
authors = ["JHIH-SIOU LI <jsli@linux.com>"]
channels = ["conda-forge"]
name = "PartSAM"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = { cmd = "bash scripts/build-deps.sh" }
eval = { cmd = "python evaluation/eval_everypart.py" }


[dependencies]
python = "3.11.*"
cuda = "12.4.*"
cuda-toolkit = "12.4.*"
gxx_linux-64 = "11.*"

[pypi-dependencies]
torch = { version = "==2.4.1", index = "https://download.pytorch.org/whl/cu124" }
torchvision = { version = "==0.19.1", index = "https://download.pytorch.org/whl/cu124" }
torchaudio = { version = "==2.4.1", index = "https://download.pytorch.org/whl/cu124" }
lightning = "==2.2"
h5py = ">=3.15.1, <4"
yacs = ">=0.1.8, <0.2"
trimesh = ">=4.11.2, <5"
scikit-image = ">=0.26.0, <0.27"
loguru = ">=0.7.3, <0.8"
boto3 = ">=1.42.59, <2"
mesh2sdf = ">=1.1.0, <2"
tetgen = ">=0.8.2, <0.9"
pymeshlab = ">=2022.2.post3, <2023"
plyfile = ">=1.1.3, <2"
einops = ">=0.8.2, <0.9"
libigl = ">=2.6.1, <3"
polyscope = ">=2.6.1, <3"
potpourri3d = ">=1.3, <2"
simple-parsing = ">=0.1.8, <0.2"
arrgh = ">=1.0.0, <2"
open3d = ">=0.18.0, <0.19"
safetensors = ">=0.7.0, <0.8"
hydra-core = ">=1.3.2, <2"
omegaconf = ">=2.3.0, <3"
accelerate = ">=1.12.0, <2"
timm = ">=1.0.25, <2"
igraph = ">=1.0.0, <2"
ninja = ">=1.13.0, <2"
vtk = ">=9.6.0, <10"
torch-scatter = { url = "https://data.pyg.org/whl/torch-2.4.0%2Bcu124/torch_scatter-2.1.2%2Bpt24cu124-cp311-cp311-linux_x86_64.whl" }
huggingface-hub = { version = ">=1.5.0, <2", extras = ["cli"] }
spconv-cu124 = ">=2.3.8, <3"

